# Funding configuration for GitHub Sponsors
# Uncomment and configure when ready to accept sponsorships

# github: [unykornai]
# patreon: supergreenenergy
# open_collective: sge
# ko_fi: supergreenenergy
# custom: ["https://supergreenenergy.com/sponsor"]
